Added `begin` and `end` to `makebm`'s json output

diff --git a/makebm b/makebm
--- a/makebm
+++ b/makebm
@@ -1,27 +1,5 @@
 #!/bin/bash
 
-
-timer_start=$(date +%s.%3N)
-timestamp=$(date +%y%m%d-%H%M)
-
-if [[ -z $cmd ]]; then
-  echo "ERROR: no cmd provided"
-  echo "Usage: option=x $0"
-  echo
-  echo "Options:"
-  echo 
-  echo " cmd         e.g.: \"/home/user/abc.out <<< /home/user/data.txt\""
-  echo " runs        e.g.: 10"
-  echo " maxt        e.g.: 56"
-  echo " tspace      e.g.: \"1,2,4,8,16,24,28,32,40\""
-  echo " prefix      e.g.: mymachine"
-  echo " postfix     e.g.: abc"
-  echo " realtime    y | n (default is y)"
-  echo " phase       e.g.: \"Kernel\""
-  echo " json        e.g.: summary.json"
-  exit 1
-fi
-
 compute_median () {
   numbers=($(printf "%s\n" "$@" | sort -n))
   count=${#numbers[@]}
@@ -37,7 +15,35 @@ compute_median () {
   echo $median
 }
 
+################################################################################
+
+if [[ -z $cmd ]]; then
+  echo "ERROR: no cmd provided"
+  echo "Usage: option=x $0"
+  echo
+  echo "Options:"
+  echo 
+  echo " cmd         e.g.: \"/home/user/abc.out <<< /home/user/data.txt\""
+  echo " runs        e.g.: 10"
+  echo " maxt        e.g.: 56"
+  echo " tspace      e.g.: \"1,2,4,8,16,24,28,32,40\""
+  echo " prefix      e.g.: mymachine"
+  echo " postfix     e.g.: abc"
+  echo " realtime    y | n (default is y)"
+  echo " timestamp   e.g.: 240730-0126"
+  echo " phase       e.g.: \"Kernel\""
+  echo " json        e.g.: summary.json"
+  exit 1
+fi
+
+timer_start=$(date +%s.%3N)
+timestamp_begin_json=$(date +'%Y-%m-%d %H:%M:%S')
+
 # setting default values
+
+if [[ -z $timestamp ]]; then
+  timestamp=$(date +%y%m%d-%H%M)
+fi
 
 if [[ -z $runs ]]; then
   runs=3
@@ -59,7 +65,7 @@ if [[ -z $json ]]; then
   json="$prefix$timestamp$postfix.json"
 fi
 
-outfileCSV="$prefix$timestamp$postfix.csv"
+outfile_csv="$prefix$timestamp$postfix.csv"
 
 if [[ -z $tspace ]]; then
   space=$(seq 1 $maxt)
@@ -99,11 +105,11 @@ echo "tspace      = $tspace"
 echo "realtime    = $realtime"
 echo "phase       = $phase"
 echo "json        = $json"
-echo "outfile     = $outfileCSV"
+echo "outfile     = $outfile_csv"
 echo "threads     = { ${space[@]} }"
 echo
 
-echo "threads,time" > $outfileCSV
+echo "threads,time" > $outfile_csv
 
 for threads in ${space[@]}; do
   total_time=0
@@ -130,7 +136,7 @@ for threads in ${space[@]}; do
       current_time=$(echo "$cmd_out" | grep -i $phase | egrep -o "[0-9]*(\.[0-9]+)?")
     fi
 
-    echo "$threads,$current_time" >> $outfileCSV
+    echo "$threads,$current_time" >> $outfile_csv
     exec_times+=($current_time)
     printf "%.3f ms (rc=%i)\n" $current_time $rc
     total_time=$(echo "$total_time+$current_time" | bc)
@@ -159,12 +165,21 @@ for threads in ${space[@]}; do
 done
 
 timer_stop=$(date +%s.%3N)
+timestamp_end_json=$(date +'%Y-%m-%d %H:%M:%S')
 elapsed=$(echo "scale=3; $timer_stop-$timer_start" | bc)
+tspace_json=$(echo ${space[@]} | tr ' ' ',')
 
-spaceCSV=$(echo ${space[@]} | tr ' ' ',')
-echo "{\"file\":\"$outfileCSV\",\"tspace\":\"${spaceCSV[@]}\",\"cmd\":\"$cmd\",\"elapsed_s\":\"$elapsed\"}" >> $json
+json_content=()
+json_content+="\"file\":\"$outfile_csv\""
+json_content+=("\"tspace\":\"${tspace_json[@]}\"")
+json_content+=("\"cmd\":\"$cmd\"")
+json_content+=("\"elapsed_s\":\"$elapsed\"")
+json_content+=("\"begin\":\"$timestamp_begin_json\"")
+json_content+=("\"end\":\"$timestamp_end_json\"")
 
-echo "\"$outfileCSV\" is ready" 
+IFS="," ; printf "{%s}\n" "${json_content[*]}" >> $json
+
+echo "\"$outfile_csv\" is ready" 
 echo "\"$json\" has been updated"
-echo "Elapsed time: $elapsed s"
 echo
+echo "Elapsed time: $elapsed s"
